### ISSUE TITLE
ImageList component does not respond to double-click

### ISSUE THREAD

**Issue by PeterPanino** [lynatan/ComponentTray#2]
ImageList component does not respond to double-click to open the ImageList editor.

**Comment by ortuagustin** [comment]
Confirm

Steps to reproduce:

1. Create new VCL or FMX app
2. Place an ImageList
3. Double click with left mouse button on the ImageList1 on the ComponentTray

Nothing happens. Expected behaviour should be open the ImageList editor

Using right click on the ImageList and clicking on Edit ImageList does bring the editor

**Comment by superswanman** [comment]
Thanks, I totally forgot to implement that.
